@startuml class_diagram
left to right direction

abstract class User{
    + name: String
    + surname: String
    + email: String
    + password: String
}

class Student extends User{
    + dateOfBirthday: Date
}
Student "0..*" --* University : enrolled

class CompanyMember extends User{

}
CompanyMember "1..*" --* Company : employ

class UniversityMember extends User{

}
UniversityMember "1..*" --* University : employ

class University{
    + universityName: String 
    + mailDomain: String
}

class Company{
    + companyName: String
    + companyDescription: String
    + mailDomain: String
}

class Internship{
    + name: String
    + dateOfPublication: Date
    + applicationStartDate: Date
    + applicationEndDate : Date
    + maxStudentsAllowed: Int
    + openForApplication: Boolean
}
Company -- "0..*" Internship : offer

class InternshipDescription{
    + description: String
    + requirements: String
    + applicationDomain: String
    + terms: String
}
InternshipDescription --* Internship : owns

class InternshipStatus{
    + interruptionRequested: Boolean
    + beginInternshipDate: Date
    + endInternshipDate: Date
}
InternshipStatus "0..*" -- Student : partecipate
InternshipStatus "0..*" -- Internship : manage
InternshipStatus *-- "0..*" InternshipComplaint : has

class InternshipComplaint{
    + title: String
    + content: String
    + dateOfCreation: Date
}

class InternshipReport{
    + title: String
    + content: String
    + dateOfCreation: Date
}
InternshipReport "0..*" -- InternshipStatus : has
InternshipReport "0..*" -- User : owner

class Request{
    + approved: Boolean 
    + dateOfCreation: Date
}
Request "0..*" -- Internship : refer
Request "0..*" -- User : requestedBy

class StudentSelectionProcess{
    + selected: SELECTION_STATUS
}

StudentSelectionProcess "0..*" -- Student : partecipate
StudentSelectionProcess "0..*" -- Internship : refer
StudentSelectionProcess -- Chat : have
StudentSelectionProcess -- Interview : have

abstract class Interview{
    + date: Date
    + details: String
    + estimatedDuration: String
}

class OnlineInterview extends Interview{
    + link: String
}

class InPersonInterview extends Interview{
    + address: String
    + room: String
}

class Feedback {
    + globalScore: Float
    + comment: String
}

Feedback "0..*" -- InternshipStatus : refer
Feedback "0..*" -- User : creator

class FieldEvaluation{
    + fieldName: String
    + description:String
    + score: Float
}
FieldEvaluation "0..*" -- Feedback : have

class Suggestion{
    + content: String
}
Suggestion "0..*" -- "0,1" CurriculumVitae : refer
Suggestion "0..*" -- "0,1" InternshipDescription : refer

class Recommendation{
    + compatibilityRate: Float
}
Recommendation "0..*" -- Internship : recommend
Recommendation "0..*" -- Student : recommend

class Chat{
}

class Message{
    + content: String
    + timestamp: Timestamp
}

User -- "0..*"  Message : sender

Message "0..*" --* Chat : contain
Student -- "0..*"  Chat : have
CompanyMember -- "0..*"  Chat : have

class CurriculumVitae{
    + CVDocument: File
}
CurriculumVitae --* Student : owns

class CVSection{
    + title: String
    + content: String
}
CVSection "1..*" --* CurriculumVitae : have

class Tag{
    + name: String
}
Tag "0..*" -- "0..*" CVSection : have
Tag "0..*" -- "0..*" InternshipDescription : have

@enduml

//review composition/relations