@startuml internshipStatus_state_diagram

state orComponent <<choice>>

[*] -> Waiting
Waiting --> Ongoing: "beginInternshipDate"\nhas been reached
Ongoing --> orComponent
orComponent --> Ended
orComponent --> Interrupted
Interrupted --> [*]
Ended --> [*]

Waiting: student was selected from the company\nand he is waitign for starting the internship
Ongoing: student performs the tasks\nassigned by the company
Ended: "endInternshipDate" has been reached
Interrupted: internship interrupted by \nthe university of the student
note right of orComponent: exclusive gateway
@enduml