@startuml UC11_diagram
hide footbox

participant "Student" as ST
participant "External statistical tool" AS EXT
participant "S&C" AS S

activate S
activate ST
ST -> S: modifyDigitalizedCV()
S --> ST: show "modification form"
ST -> S: confirmModifications(changes)
S -> EXT: updateStudent(studentID, newSetOfTags)
activate EXT
EXT --> S: ok
deactivate EXT
S --> ST: show the updated version of the digitalized CV
@enduml