@startuml UC12_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S

activate ST
activate S
ST -> S: uploadNewCVDocument()
S --> ST: show file selection dialog
ST -> S: selectFile(file)
alt file extension is valid
    S -> S: storeCVDocument(file)
    S --> ST: showMessage("document uploaded")
else file extension is not valid
    S --> ST: showError("invalid file extension")
end
S --> ST: show personal page
@enduml