@startuml UC14_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S

activate ST
activate S

ST -> S: applySuggestion()
S --> ST: show digitalized curriculum form
ST -> ST: insertInformations()
ST -> S: confirmModifications()
S --> ST: show personal page
@enduml