@startuml UC14_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "Company Member" as CM

activate ST
activate S
ST -> S: selectInternship(internshipName)
S --> ST: internship details
ST -> S: sendRequest(request)
S -> S:  checkNumberRequest()
alt First time the request is sent
    S -> S: retrieveStudentInfo()
    S ->> CM : sendRequest(request)
    activate CM
    deactivate CM
    S --> ST : ok
else else
    S --> ST: error message
end
@enduml