@startuml UC16_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "Company Member" as CM

activate ST
activate S
ST -> S: matchChoice(choice)
alt Internship is still available
    activate CM
    alt Student has accepted the match
        S -> S  : createChat(student, companyMember)
        S ->> CM : notifyChoice(choice, student)
        S ->> CM : openChat(student)
        S --> ST : new chat
    else Student has rejected the match
        S ->> CM : removeCandidate(student)
    end
else Internship closed
    S --> ST: error message
end
@enduml