@startuml UC16_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "Company Member" as CM

activate ST
activate S
ST -> S: selectInternship(internshipName)
S --> ST: internship details
ST -> S: sendRequest(request)
alt Internship is open
    alt First time the request is sent
        S -> CM : sendRequest(request)
        activate CM
        CM --> S : ok
        deactivate CM
        S --> ST : ok
    else else
        S --> ST: error message
    end
else else
    S --> ST: error message
end
@enduml