@startuml UC17_diagram
hide footbox

participant "Company Member" as CM
participant "S&C" AS S
participant "Student" as ST

activate CM
activate S
CM -> S: matchChoice(choice, student)
alt Internship is still available
    S -> ST : sendChoice(choice, companyMember)
    activate ST
    alt Student has accepted
        S -> CM : addCandidate(student)
        S -> CM : openChat(student)
        S -> ST : openChat(companyMember)
    else 
        S -> CM : removeFromCandidate(student)
    end
else 
    S -> CM: error message
end
@enduml