@startuml UC18_diagram
hide footbox

participant "Company Member" as CM
participant "S&C" AS S
participant "Student" as ST

activate CM
activate S

CM -> S: scheduleMeeting()
S --> CM: form for meeting details
CM -> S : submitMeeting(meeting)
S -> S : checkMeeting(meeting)
loop meeting information are correct
    S --> CM: error message
    CM -> S : submitMeeting(meeting)
    S -> S : checkMeeting(meeting)
end
S -> ST : sendNotification()
activate ST
S -> ST : addMeeting(meeting)
S --> CM : addMeeting(meeting)
deactivate ST
alt meeting overlaps with other scheduled events 
    S -> CM: warning message
end
@enduml