@startuml UC19_diagram
hide footbox

participant "Company Member" as CM
participant "S&C" AS S
participant "Student" as ST

activate CM
activate S

CM -> S: showCandidates(internshipName)
S --> CM: list of candidates
CM -> S : selectStudent(student)
S --> CM : student's info
CM -> S : admission(result, companyMember)
S -> S : remotion of the student from the list of candidates
alt Student is accepted
    S -> S  : collectInternshipInfo()
    S ->> ST : sendOffer(contract)
    activate ST
    S --> CM : updated list of candidates
else Student is rejected
    S -> ST : sendResult(result)
    ST --> S : ok
    S -> ST : deleteChat()
    ST --> S : ok
    S --> CM : page with the updated list of candidates with the chat deleted
end 
@enduml