@startuml UC19_diagram
hide footbox

participant "Company Member" as CM
participant "S&C" AS S
participant "Student" as ST

activate CM
activate S
CM -> S: matchChoice(choice, student)
alt Internship is still available
    activate ST
    alt Company member has accepted the student
        S -> S  : createChat(student, companyMember)
        S --> CM : page with the new chat and the updated list of candidates
        S ->> ST : sendChoice(choice, companyMember)
        S ->> ST : openChat(companyMember)
    else else
        S --> CM : new list of candidates without the student
    end
else else
    S --> CM: error message
end
@enduml