@startuml UC22_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "Company Member" as CM
participant "University Member" as UM

activate ST
activate S

ST -> S : createReport()
S --> ST : report to be filled
ST -> S : submitReport(report)
loop until report is not empty
    S --> ST : error message
    ST -> S : submitReport(report)
end
S --> ST : updated list of reports
S ->> CM : addReport(report)
activate CM
S ->> UM : addReport(report)
activate UM
@enduml