@startuml UC22_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "Company Member" as CM

activate ST
activate S

ST -> S: offerDecision(choice)
S -> S : retrieveInternshipInfo(student)
S -> S : deleteChat(student, company member)
S  -> CM : sendDecision(choice, student)
activate CM
CM --> S : ok
S -> CM : deleteChat()
CM --> S : ok
S --> ST : page without the chat
@enduml