@startuml UC26_diagram
hide footbox

participant "Student" as ST
participant "S&C" AS S
participant "University Member" as UM
participant "Company Member" as CM

activate ST
activate S

ST -> S : writeComplaint()
S --> ST : complaint to write
ST -> S : submitComplaint(complaint)
S  -> S : checkComplaint()
loop until complaint is not empty
    S -> ST : showError(message)
    ST -> S : submitComplaint(complaint)
    S  -> S : checkComplaint()
end
S -> S : retrieveStudentInformation()
S --> ST : updated list of complaints
S -> UM : addComplaint(complaint)
activate UM
UM --> S : ok
S -> CM : addComplaint(complaint)
activate CM
CM --> S : ok
@enduml