@startuml UC2_diagram
hide footbox

participant "Company member" as CM
participant "External statistical tool" AS EXT
participant "eMail provider" as EP
participant "S&C" AS S

CM -> S: registerAsCompanyMember()
activate S
activate CM
S --> CM: show registration form
S --> CM: list of all registered companies
alt company is registered to the system
    CM -> S: register(name, surname, dateOfBirth, password, emailAddress, company)
    S -> S: checkData()
    alt email address is valid
        S -> EP: sendEmailRequest(emailAddress, text)
        activate EP
        EP --> S: ok
        EP -> CM: sendEmail(email)
        deactivate EP
        alt user confirm the email address within one day of registration
            CM -> S: confirmEmailAddress()
            S -> S: addUser()
        else user does not confirm the email address
            S --> CM: showError("registration canceled")
        end
    else email is already registered to the system
        S --> CM: showError("user already registered")
    else email address is not linked to the company provided
        S --> CM: showError("invalid email domain")
    end
else company is not registered to the system
    CM -> S: createCompanyRequest()
    S --> CM: show company registration form
    CM -> S: confirmRegistration(userInformations, companyName, companyDescription)
    S -> EP: sendEmailRequest(emailAddress, text)
    activate EP
    EP --> S: ok
    EP -> CM: sendEmail(email)
    deactivate EP
    alt user confirm the email address within one day of registration
        CM -> S: confirmEmailAddress()
        S -> S: addCompany()
        S -> EXT: newCompany(companyID)
        activate EXT
        EXT --> S: ok
        deactivate EXT
        S -> S: addUser()
    else user does not confirm the email address
        S --> CM: showError("registration canceled")
    end
end
@enduml