@startuml UC4_diagram
hide footbox

participant "University member" as UM
participant "S&C" AS S

UM -> S: loginRequest()
activate S
activate UM
S --> UM: show login form
UM -> S: confirmLogin(email, password)

S -> S: checkCredentials
alt credentials are valid
    S --> UM: show homepage
else invalid credentials
    S --> UM: showError("invalid credentials")
end
@enduml