@startuml UC5_diagram
hide footbox

participant "Student" as ST
participant "External statistical tool" AS EXT
participant "S&C" AS S

ST -> S: loginRequest()
activate S
activate ST
S --> ST: show login form
ST -> S: confirmLogin(email, password)
S -> S: checkCredentials
alt credentials are valid
    S -> EXT: findStudentRecommendations(studentID)
    activate EXT
    EXT --> S: [(companyID, internshipID), ...]
    deactivate EXT
    S --> ST: show homepage
else invalid credentials
    S --> ST: showError("invalid credentials")
end
@enduml