@startuml UC6_diagram
hide footbox

participant "Company member" as CM
participant "External statistical tool" AS EXT
participant "S&C" AS S

CM -> S: loginRequest()
activate S
activate CM
S --> CM: show login form
CM -> S: confirmLogin(email, password)
S -> S: checkCredentials
alt credentials are valid
    S -> EXT: findCompanyRecommendations(companyID)
    activate EXT
    EXT --> S: [(studentID, internshipID), ...]
    deactivate EXT
    S --> CM: show homepage
else invalid credentials
    S --> CM: showError("invalid credentials")
end
@enduml