@startuml UC7_diagram
hide footbox

participant "Company member" as CM
participant "External statistical tool" AS EXT
participant "S&C" AS S

activate S
activate CM
CM -> S: createInternship()
S --> CM: show internship form

CM -> S: confirm(internshipData)
S -> EXT: newInternship(companyID, internshipID, tags)
activate EXT
EXT --> S: ok
deactivate EXT
S --> CM: show internship details
@enduml