@startuml UC8_diagram
hide footbox

participant "Company member" as CM
participant "External statistical tool" AS EXT
participant "S&C" AS S

activate S
activate CM
CM -> S: modifyInternship(internshipName)
S --> CM: show internship form
CM -> S: seeModifications()
S --> CM: modified fields
alt company member confirms modifications
    CM -> S: confirm(modifications)
    S -> EXT: updateInternship(companyID, internshipID, newSetOfTags)
    activate EXT
    EXT --> S: ok
    deactivate EXT
else company member does not confirm modifications
    CM -> S: revertModifications()
    S --> CM: showError("procedure canceled")
end
S --> CM: show internship page
@enduml