@startuml use_cases_diagram1
left to right direction

together{
    actor :Student: as ST
    actor :Company member: as CM
    actor :University member: as UM
    actor :User: as U
}

rectangle "S&C system"{
    usecase (User writes a message) as UC23
    usecase (Student writes a report) as UC24
    usecase (Company member writes a report) as UC25
}

U --> UC23 : initiate

ST --> UC24: initiate
CM --> UC24: participate
UM --> UC24 : participate

ST -> UC25 : participate
CM --> UC25: initiate
UM --> UC25: participate
@enduml