@startuml use_cases_diagram3
left to right direction

together{
    actor :Student: as ST
    actor :Company member: as CM
    actor :External statistical analysis tool: as STAT
    actor :eMail provider: as EMAIL
}

rectangle "S&C system"{
    usecase (Modify the digitalized curriculum vitae version) as UC11
    usecase (Upload a new CV document) as UC12
    usecase (Notify new recommendations) as UC13
}

ST -> UC11: initiate
STAT -> UC11: participate

ST --> UC12: initiate

STAT -> UC13: participate
ST --> UC13: participate
CM --> UC13: participate
EMAIL --> UC13: participate
@enduml