@startuml use_cases_diagram5
left to right direction

together {
    actor :Student: as ST
    actor :Company member: as CM
    actor :External videoconference tool: as EVT
}

rectangle "S&C system" {
    usecase (Company member schedules the meeting) as UC20
    usecase (Company member communicates the result of the interview) as UC21
    usecase (Student decides on the offer) as UC22
}

CM  --> UC20 : initiate
ST  --> UC20 : participate
EVT --> UC20 : participate

CM -> UC21 : initiate
ST --> UC21 : participate

ST ---> UC22 : initiate
CM ---> UC22 : participate
@enduml