@startuml use_cases_diagram1
left to right direction

together{
    actor :Student: as ST
    actor :Company member: as CM
    actor :University member: as UM
    actor :External statistical analysis tool: as STAT
    actor :eMail provider: as EMAIL
}

rectangle "S&C system"{
    usecase (Registration of a university member) as UC1
    usecase (Registration of a company member) as UC2
    usecase (Registration of a student) as UC3
    usecase (Login of a university member) as UC4
    usecase (Login of student) as UC5
    usecase (Login of company member) as UC6
}

UM -> UC1: initiate
EMAIL -> UC1: participate

CM --> UC2: initiate
EMAIL --> UC2: participate
STAT --> UC2: participate

ST -> UC3: initiate
EMAIL --> UC3: participate
STAT --> UC3: participate

UM -> UC4: initiate

ST -> UC5: initiate
STAT -> UC5: participate

CM -> UC6: initiate
STAT -> UC6: participate
@enduml
