@startuml use_cases_diagram2
left to right direction

together{
    actor :Student: as ST
    actor :Company member: as CM
    actor :External statistical analysis tool: as STAT
}

rectangle "S&C system"{
    usecase (Creation of an internship) as UC7
    usecase (Modify an internship) as UC8
    usecase (Delete an internship) as UC9
    usecase (Searching for an internship by means of keywords) as UC10
}

CM --> UC7: initiate
STAT -> UC7: participate

CM --> UC8: initiate
STAT -> UC8: participate

CM -> UC9: initiate
STAT -> UC9: participate

ST --> UC10: initiate
STAT -> UC10: participate
@enduml
