@startuml deployment_diagram

node "User Device" {
  artifact "Browser" as UserBrowser
}

node "Perimeter Firewall" {
  artifact "Firewall system" as PerimeterFW
}

node "Load Balancer" as LoadBalancer {
  artifact "Load Balancer system" as LBSystem
}

node "Application Server1" as AppServer1N {
  artifact "Application Server" as AppServer1
}

node "Application Server2" as AppServer2N {
  artifact "Application Server (Replica 1)" as AppServer2
}

node "Application Server1" as AppServer3N {
  artifact "Application Server (Replica 2)" as AppServer3
}

node "Database Server" as DBN {
  artifact "DBMS system" as DBMS
  database "Database" as DB
}

node "Internal Firewall" {
  artifact "Firewall system" as InternalFW
}


UserBrowser --> PerimeterFW : "HTTPS/WebSocket"
PerimeterFW --> LBSystem : "HTTPS/WebSocket"
LBSystem ---> AppServer1 : "HTTPS/WebSocket"
LBSystem ---> AppServer2 : "HTTPS/WebSocket"
LBSystem ---> AppServer3 : "HTTPS/WebSocket"

AppServer1 ---> InternalFW : "TCP/IP"
AppServer2 ---> InternalFW : "TCP/IP"
AppServer3 ---> InternalFW : "TCP/IP"

InternalFW --> DBMS : "SQL Queries / TCP/IP"
DBMS --> DB : SQL Queries
@enduml