@startuml RV11_diagram
hide footbox

participant "Student" as S 
participant "Web App" as W
participant "Controller" AS C
participant "CV Manager" AS CM
participant "Suggestion Manager" as SM
participant "Reccomendation Manager" as RM
participant "External statistical tool" AS EXT
participant "Data Manager" AS DM
participant "DBMS" AS RD



activate S
activate W
S -> W: click modify button
W --> S: show modification form
S -> S: insert text modification
S -> W: confirm modification
W -> C: modifySectionDescription(text, section)
activate C
C -> CM: modifySectionDescription(text, section)
activate CM

CM -> DM: modifyCV(text, section)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> CM: ok
deactivate DM 

CM -> RM: updateCV(digitalizedCV)
activate RM
RM -> EXT: updateEntity(ENTITYTYPE.STUDENT, tagsRemoved, tagsAdded, studentID)
activate EXT
EXT --> RM: ok
deactivate EXT
RM --> CM: ok
deactivate RM

CM -> SM: getCVSuggestions(digitalizedCvSection)
activate SM
SM --> CM: new suggestions
deactivate SM
CM --> C: ok
deactivate CM
C --> W: ok
deactivate C
W --> S: show updates


@enduml

"The function updateEntity(ENTITYTYPE, tagsRemoved, tagsAdded, userID) updates the entity in the statistical analysis tool by specifying the 
tags that were removed and the tags that were added."