@startuml RV12_diagram
hide footbox

participant "Student" as S 
participant "Web App" as W
participant "Controller" AS C
participant "CV Manager" AS CM
participant "Data Manager" AS DM
participant "DBMS" AS RD

activate S
activate W

S -> W: click upload new CV document
W --> S: show file selection dialog
S -> S: select new CV file 
S -> W: confirm new CV file

alt file extension is valid
W -> C: publishCV(CVfile)
activate C
C -> CM: publishCV(CVfile)
activate CM
CM -> CM: store(CVfile)
CM -> DM: addCV(CVfile)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> CM: ok
deactivate DM
CM --> C: ok
deactivate CM
C --> W: ok
deactivate C 
W --> S: document uploaded

else file extension is not valid
W --> S: error invalid file extension
end

W --> S: show updates

@enduml

"The Curriculum Vitae file is stored in the CV Manager component, while the DBMS saves its location."