@startuml RV13_diagram
hide footbox

actor "Student" as S 
actor "Company Member" as C
participant "Recommendation Manager" as RM
participant "External statistical tool" as SAT
participant "Data Manager" as DM
participant "Email Manager" as EM
participant "DBMS" as RD
participant "Email Server" as E


activate S
activate C
activate RM

RM -> SAT: getNewRecommendations(ENTITYTYPE.STUDENT) 
activate SAT
SAT --> RM: new students recommendation
deactivate SAT
RM -> SAT: getNewRecommendations(ENTITYTYPE.COMPANY) 
activate SAT
SAT --> RM: new company recommendation
deactivate SAT
RM -> DM: newRecommendation(studentID, newRecommendation)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> RM: ok
deactivate DM
RM -> DM: newRecommendation(companyID, newRecommendation)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> RM: ok
deactivate DM
RM -> EM: sendRecommendationEmail(users)
activate EM
EM -> E: sendEmail(email)
activate E
E --> EM: ok
EM --> RM: ok
deactivate EM
deactivate RM
E -> S: sendEmail(email)
E -> C: sendEmail(email)
deactivate E





@enduml


