@startuml RV13_diagram
hide footbox

actor "Student" as S 
actor "Company Member" as C
participant "Recommendation Manager" as RM
participant "Statistical Analysis Tool" as SAT
participant "Data Manager" as DM
participant "Email Manager" as EM
participant "DBMS" as RD
participant "Email Server" as E


activate S
activate C
activate RM

RM -> SAT: getNewRecommendations(ENTITYTYPE.STUDENT) 
activate SAT
SAT --> RM: new students recommendation
deactivate SAT
RM -> SAT: getNewRecommendations(ENTITYTYPE.COMPANY) 
activate SAT
SAT --> RM: new company recommendation
deactivate SAT
RM -> DM: updateRecomendation(newRecommendation)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> RM: ok
deactivate DM
RM -> EM: sendRecommendationEmail(users)
activate EM
EM -> E: sendEmail(email)
activate E
E --> EM: ok
EM --> RM: ok
deactivate EM
deactivate RM
E -> S: sendEmail(email)
E -> C: sendEmail(email)
deactivate E





@enduml


"The function getNewRecommendations(entityType) retrieves all the new recommendations related to entities of the type specified by the parameter 
entityType"
"The diagram represents only two users, a Student and a Company Member ( company members receive recommendation associated to their company), 
who act as representatives of their respective categories. However, emails are sent to all users with new recommendations (which may include none)"