@startuml RV15_diagram
hide footbox

actor "Company Member" as COM 
participant "Web App" as W
participant "Controller" AS C
participant "Internship Proposal Manager" AS I
participant "Suggestion Manager" as SM
participant "Recommendation Manager" as RM
participant "External statistical tool" AS EXT
participant "Data Manager" AS DM
participant "DBMS" AS RD



activate COM
activate W
COM -> W: click apply suggestion
W --> COM: show modification form
COM -> COM: insert text modification
COM -> W: confirm modification
W -> C: modifyInternshipDetails(internshipID, internshipDetails)
activate C
C -> I: modifyInternshipDetails(internshipID, internshipDetails)
activate I

I -> DM: modifyInternshipDetails(internshipID, internshipDetails)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: ok
deactivate RD
DM --> I: ok
deactivate DM 
I -> RM: updateInternshipTags(companyID, internshipID, tags)
activate RM
RM -> EXT: updateEntity(ENTITYTYPE.INTERNSHIP, tagsRemoved, tagsAdded, internshipID)
activate EXT
EXT --> RM: ok
deactivate EXT
RM --> I: ok
deactivate RM

I -> SM: getInternshipSuggestion(internshipDetails)
activate SM
SM --> I: new suggestions
deactivate SM
I --> C: ok
deactivate I
C --> W: ok
deactivate C
W --> COM: show updates


@enduml


