@startuml RV16_diagram
hide footbox

actor "Student" as S 
participant "Web App Student" as W
participant "Controller" AS C
participant "Internship Proposal Manager" as IP
participant "Match Manager" as M
participant "Data Manager" as DM
participant "DBMS" as RD
participant "Notification Manager" as NM
participant "Web App Company Member" as WA
actor "Company Member" as CM




activate S
activate W
activate CM
activate WA

S -> W: click on internship proposal
W -> C: getInternshipDetails(internshipID)
activate C
C -> IP: getInternshipDetails(internshipID)
activate IP
IP -> DM: getInternshipDetails(internshipID)
activate DM
DM -> RD: executeStatement(statement)
activate RD
RD --> DM: internship details
deactivate RD
DM --> IP: internship details
deactivate DM
IP --> C: internship details
deactivate IP
C --> W: internship details
deactivate C
W --> S: show details
S -> W: click send match proposal
alt Internship is open
    alt First time the match proposal is sent
        W ->C: studentMatchProposal(studentID, internshipID)
        activate C

        C -> M: studentMatchProposal(studentID, internshipID)
        activate M

        M -> NM: sendNotifyNewMatch(matchProposal)
        activate NM

        alt Company Member active
            NM -> WA: showNotifyNewMatch(matchProposal)
            WA -> CM: show new match
            WA --> NM: ok
            NM --> M: ok
        else Company Member inactive
            NM --> M: company member offline
        end
        deactivate NM
        M -> DM: addMatchProposal(matchProposal)
        activate DM
        DM -> RD: executeStatement(statement)
        activate RD
        RD --> DM: ok
        deactivate RD
        DM --> M: ok
        deactivate DM
        M --> C: ok
        deactivate M
        C --> W: ok
        deactivate C
        W --> S: match proposal sent
    else else
        W --> S: error match proposal already sent
    end
else else
    W --> S: error internship closed
end
@enduml

