@startuml RV20_diagram
hide footbox

actor "Company member" as CM
participant "Web App Company member" as WACM
participant "Controller" as C
participant "Selection Manager" as SM
participant "Interview Scheduler" as IS
participant "External Videoconference tool" as EV
participant "Data Manager" as DM
participant "DBMS" as DB
participant "Notification Manager" as NM
participant "Web App Student " as WAST
actor "Student" as ST

activate CM

activate WACM
CM -> WACM : press button to schedule the meeting
WACM --> CM : form page
CM -> CM    : fill the meeting form
CM -> WACM  : click the submit button
WACM -> WACM : checkInfo(form)
loop until meeting information are correct
WACM --> CM : error
CM -> CM  : fill the meeting form
CM -> WACM  : click the submit button
WACM -> WACM : checkInfo(form)
end
WACM -> C   : submitMeeting(form)
activate C
C  -> SM  : submitMeeting(form)
activate SM
SM -> IS  : submitMeeting(form)
activate IS
alt online meeting
IS -> EV  : generateLink(date)
activate EV
EV --> IS : link
deactivate EV
IS -> IS  : attachLink(meeting, link)
end
IS --> SM  : meeting
deactivate IS
SM ->  DM  : addMeeting(meeting)
activate DM
DM ->  DB  : executeStatement(statement)
activate DB
DB --> DM  : ok
deactivate DB
DM --> SM  : ok  
deactivate DM
SM ->  DM  : findOverlappingEvents(meeting)
activate DM
DM ->  DB  : executeStatement(statement)
activate DB 
DB --> DM  : tuples of overlapping events
deactivate DB 
DM --> SM  : list of overlapping events
deactivate DM
alt list of overlapping events is not empty
SM ->  IS  : attachWarning(meeting, overlappingEvents)
activate IS
IS -> IS   : attachWarning(meeting, overlappingEvents)
IS --> SM  : meeting
deactivate IS
end
SM -> NM   : sendNotifyMeeting(meeting)
activate NM
alt student is online
activate WAST
activate ST
NM -> WAST : showNotifyMeeting(meeting)
WAST -> ST : page with the meeting in the internship reminder, optionally displaying the warning
WAST --> NM : ok
deactivate WAST
deactivate ST
end
NM --> SM   : ok
deactivate NM
SM --> C   : meeting
deactivate SM
C  --> WACM  : meeting
deactivate C
WACM --> CM  : page with the meeting in the internship reminder, optionally displaying the warning
@enduml