@startuml RV25temp
hide footbox

participant "User" as U
participant "Web App User" AS WAU
participant "Controller" as C
participant "Internship Manager" as IM
participant "Data Manager" as DM
participant "DBMS" as DB
participant "Notification Manager" as NM
participant "Other User" as OU
participant "Web App other user " AS WAOU
participant "Web App University member" AS WAUM
participant "University member" AS UM

activate U
activate WAU
U -> WAU : click the create report button
WAU --> U : report
WAU -> WAU : checkReport(report)
loop until report is not empty
    WAU --> U : error page
    U -> WAU  : report
    WAU -> WAU : checkReport(report)
end
WAU -> C : submiteReport(report)
activate C
C -> IM    : submitReport(report)
activate IM
IM -> DM : addReport(report)
activate  DM
DM -> DB : executeStatement(statement)
activate DB
DB --> DM : ok
deactivate DB
DM --> IM : ok
deactivate DM
IM -> NM : notifyReport(report)
activate NM
alt company member(student) is online if user is student(company member)
    activate WAOU
    activate OU
    NM -> WAOU : showReport(report)
    WAOU -> OU : page with the new list of reports
    WAOU --> NM : ok
    deactivate WAOU
    deactivate OU
end 
alt university member is online
    NM -> WAUM : showReport(report)
    activate WAUM
    activate UM
    WAUM -> UM : page with the new list of reports
    WAUM --> NM : ok
    deactivate WAUM
    deactivate UM
end 
NM --> IM : ok
deactivate NM
IM --> C : ok
deactivate IM
C --> WAU : ok 
deactivate C
WAU --> U : page with the new list of reports
@enduml