@startuml RV25_diagram
hide footbox

actor "Company member" as CM
participant "Web App Company member" AS WACM
participant "Controller" as C
participant "Internship Status Manager" as IM
participant "Data Manager" as DM
participant "DBMS" as DB
participant "Notification Manager" as NM
participant "Web App student" AS WAST
actor "Student" as ST
participant "Web App University member" AS WAUM
actor "University member" AS UM

activate CM
activate WACM
CM -> WACM : click the create report button
WACM --> CM : report
CM -> CM   : write report
CM -> WACM : click the submit report button
WACM -> WACM : checkReport(report)
loop until report is not empty
    WACM --> CM : error page
    CM -> CM   : write report
    CM -> WACM : click the submit report button
    WACM -> WACM : checkReport(report)
end
WACM -> C : submiteReport(report)
activate C
C -> IM    : submitReport(report)
activate IM
IM -> DM : addReport(report)
activate  DM
DM -> DB : executeStatement(statement)
activate DB
DB --> DM : ok
deactivate DB
DM --> IM : ok
deactivate DM
IM -> NM : notifyReport(report)
activate NM
alt student is online
    activate WAST
    activate ST
    NM -> WAST : showReport(report)
    WAST -> ST : page with the new list of reports
    WAST --> NM : ok
    deactivate WAST
    deactivate ST
end 
alt university member is online
    NM -> WAUM : showReport(report)
    activate WAUM
    activate UM
    WAUM -> UM : page with the new list of reports
    WAUM --> NM : ok
    deactivate WAUM
    deactivate UM
end 
NM --> IM : ok
deactivate NM
IM --> C : ok
deactivate IM
C --> WACM : ok 
deactivate C
WACM --> CM : page with the new list of reports
@enduml