@startuml RV29_diagram
hide footbox

participant "Internship Proposal Manager" as IM
participant "Data Manager" as DM
participant "DBMS" as DB
participant "Recommendation manager" as RM
participant "External statistical tool" as ESAT

activate IM
IM -> DM   : closeInternship(internshipID)
activate DM
DM -> DB   : executeStatement(statement)
activate DB
DB --> DM  : ok
deactivate DB
DM --> IM  : ok
deactivate DM

IM -> DM: getCompanyIDByInternship(internshipID)
activate DM
DM -> DB: executeStatement(statement)
activate DB
DB --> DM: company ID
deactivate RD
DM --> IM: company ID
deactivate DM

IM -> RM   : deleteInternship(companyID, internshipID)
activate RM
RM -> ESAT   : removeEntity(ENTITYTYPE.INTERNSHIP, internshipID, companyID)
activate ESAT
ESAT --> RM : ok
deactivate ESAT
RM --> IM  : ok
deactivate RM
@enduml