@startuml RV9_diagram
hide footbox

actor "Company Member" as CM
participant "Web App" as W
participant "Controller" as C
participant "Internship Proposal Manager" as I
participant "Recommendation Manager" as RE
participant "Data Manager" as DM
participant "DBMS" as RD
participant "External statistical tool" AS EXT

activate CM
activate W
activate C
CM -> W: click "Delete internship" button
W --> CM: show "deletion confirmation" banner
alt company member confirms the deletion
    CM -> W: click "Confirm" button
    W -> C: deleteInternship(internshipID)
    C -> I: deleteInternship(internshipID)
    activate I

    I -> DM: deleteInternshipProposal(internshipID)
    activate DM
    DM -> RD: executeStatement(statement)
    activate RD
    RD --> DM: ok
    deactivate RD
    DM --> I: ok
    deactivate DM

    I -> DM: getCompanyID(companyMemberEmailAddress)
    activate DM
    DM -> RD: executeStatement(statement)
    activate RD
    RD --> DM: company ID
    deactivate RD
    DM --> I: company ID
    deactivate DM

    I -> RE: deleteInternship(companyID, internshipID)
    activate RE
    RE -> EXT: deleteEntity(ENTITYTYPE.INTERNSHIP, companyID, internshipID)
    activate EXT
    EXT --> RE: ok
    deactivate EXT
    RE --> I: ok
    deactivate RE
    I --> C: ok
    deactivate I
    C --> W: ok
else company member does not confirm the deletion
    CM -> W: click "Cancel" button
end
W --> CM: show internships page
@enduml